In [2]:
import torch

In [3]:
x = torch.rand(2,5)
x

tensor([[0.3884, 0.7110, 0.1605, 0.0544, 0.1122],
        [0.0359, 0.5584, 0.2509, 0.5216, 0.6192]])

In [4]:
torch.zeros(3,5).scatter(0,torch.tensor([[0, 1, 2, 0, 0], [2, 0, 0, 1, 2]]),x)

tensor([[0.3884, 0.5584, 0.2509, 0.0544, 0.1122],
        [0.0000, 0.7110, 0.0000, 0.5216, 0.0000],
        [0.0359, 0.0000, 0.1605, 0.0000, 0.6192]])

In [5]:
x = torch.rand(3,3)
x

tensor([[0.9963, 0.2453, 0.9985],
        [0.9758, 0.1066, 0.5751],
        [0.4731, 0.9228, 0.4539]])

In [6]:
torch.zeros(3,9).scatter(1,torch.tensor([[0, 3, 6], [1, 4, 7], [2, 5, 8]]),x)

tensor([[0.9963, 0.0000, 0.0000, 0.2453, 0.0000, 0.0000, 0.9985, 0.0000, 0.0000],
        [0.0000, 0.9758, 0.0000, 0.0000, 0.1066, 0.0000, 0.0000, 0.5751, 0.0000],
        [0.0000, 0.0000, 0.4731, 0.0000, 0.0000, 0.9228, 0.0000, 0.0000, 0.4539]])

In [7]:
a = torch.ones((3,9))
a

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [8]:
a.scatter(1,torch.tensor([[0, 3, 6], [1, 4, 7], [2, 5, 8]]),x)

tensor([[0.9963, 1.0000, 1.0000, 0.2453, 1.0000, 1.0000, 0.9985, 1.0000, 1.0000],
        [1.0000, 0.9758, 1.0000, 1.0000, 0.1066, 1.0000, 1.0000, 0.5751, 1.0000],
        [1.0000, 1.0000, 0.4731, 1.0000, 1.0000, 0.9228, 1.0000, 1.0000, 0.4539]])

In [9]:
a.scatter_add(1,torch.tensor([[0, 3, 6], [1, 4, 7], [2, 5, 8]]),x)

tensor([[1.9963, 1.0000, 1.0000, 1.2453, 1.0000, 1.0000, 1.9985, 1.0000, 1.0000],
        [1.0000, 1.9758, 1.0000, 1.0000, 1.1066, 1.0000, 1.0000, 1.5751, 1.0000],
        [1.0000, 1.0000, 1.4731, 1.0000, 1.0000, 1.9228, 1.0000, 1.0000, 1.4539]])

# Mapping sequence to vocabulary space

In [15]:
batch_size = 32
vocab_size = 1000
max_len = 50

random_sequence_index = torch.randint(low=0, high=vocab_size, size=(batch_size, max_len))
random_sequence_tensor = torch.rand((batch_size, max_len))
random_sequence_tensor_score = torch.nn.functional.softmax(random_sequence_tensor, dim=-1)

random_sequence_vocab = torch.zeros((batch_size, vocab_size)).scatter(1, random_sequence_index, random_sequence_tensor_score)

In [16]:
random_sequence_tensor_score.shape

torch.Size([32, 50])

In [17]:
random_sequence_vocab.shape

torch.Size([32, 1000])